# P-ROC Game Description file for Judge Dredd
PRGame:
    machineType: wpc
PRFlippers:
    - flipperLwR
    - flipperLwL
    - flipperUpR
    - flipperUpL
PRBumpers:
    - slingL
    - slingR
PRSwitches:
    flipperLwR:
        number: SF2
    flipperLwL: 
        number: SF4
    flipperUpR: 
        number: SF6
    flipperUpL: 
        number: SF8
    exit: 
        number: SD5
    down: 
        number: SD6
    up: 
        number: SD7
    enter: 
        number: SD8
    fireL:
        number: S11
    fireR:
        number: S12
    startButton:
        number: S13
    shooterL:
        number: S15
    outlaneL:
        number: S16
    inlaneL:
        number: S17
    coinDoor:
        number: S22
    inlaneR:
        number: S34
    subwayEnter1:
        number: S37
    subwayEnter2:
        number: S38
    shooterR:
        number: S41
    buyIn:
        number: S31
    outlaneR:
        number: S42
    inlaneFarR:
        number: S43
    superGame:
        number: S44
    slingL: 
        number: S51
    slingR: 
        number: S52
    captiveBall2:
        number: S53
    dropTargetJ:
        number: S54
    dropTargetU:
        number: S55
    dropTargetD:
        number: S56
    dropTargetG:
        number: S57
    dropTargetE:
        number: S58
    magnetOverRing:
        number: S71
    popperL:
        number: S73
    popperR:
        number: S74
    rightRampExit:
        number: S76
    globePosition2:
        number: S77
    trough1:
        number: S81
    trough2:
        number: S82
    trough3:
        number: S83
    trough4:
        number: S84
    trough5:
        number: S85
    trough6:
        number: S86
    troughTop:
        number: S87
PRCoils:
    flipperLwRMain: 
        number: 32
    flipperLwRHold: 
        number: 33
    flipperLwLMain: 
        number: 34
    flipperLwLHold: 
        number: 35
    flipperUpRMain: 
        number: 36
    flipperUpRHold: 
        number: 37
    flipperUpLMain: 
        number: 38
    flipperUpLHold: 
        number: 39
    craneMagnet:
        number: C01
    popperL:
        number: C02
    popperR:
        number: C03
    crane:
        number: C04
    resetDropTarget:
        number: C05
    globeMotor:
        number: C06
    shooterR:
        number: C08
    shooterL:
        number: C09
    trough:
        number: C13
    slingL: 
        number: C15
    slingR: 
        number: C16
    flasherPursuitL:
        number: C21
    flasherPursuitR:
        number: C22
    flasherBlackout:
        number: C23
    flasherCursedEarth:
        number: C24
    flashersLowerLeft:
        number: C25
    flasherGlobe:
        number: C26
    flashersRtRamp:
        number: C27
    flashersInsert:
        number: C28
PRLamps:
    buyIn:
        number: L38
    dropTargetJ:
        number: L71
    dropTargetU:
        number: L72
    dropTargetD:
        number: L73
    dropTargetG:
        number: L74
    dropTargetE:
        number: L75
    multiballJackpot:
        number: L77
    superGame:
        number: L87
    startButton:
        number: L88
    gi01:
        number: G01
    gi02:
        number: G02
    gi03:
        number: G03
    gi04:
        number: G04
    gi05:
        number: G05
