# P-ROC Game Description file a sample machine using PDBs (PinballControllers.com Driver Boards)
PRGame:
    machineType: pdb
    numBalls: 4
PRFlippers:
    - flipperLwR
    - flipperLwL
PRBumpers:
    - slingl
    - slingr
PRSwitches:
    # **** Format ****
    # name:
    #   number: <number>
    #   type: <type>
    #
    #   <number> can be: SDx (Dedicated switch, x = P-ROC input) (valid x's are 0-32)
    #                    Sx  (Matrix switch, x = column (P-ROC output) * 16 + row (P-ROC input),
    #                        Note - valid columns are 1-8, valid rows are 1-16
    #                    x   (P-ROC switch #, no translation necessary)
    #   <type> can be: 'NO' (normally open.  This is the default; so no need to use this)
    #                  'NC' (normally closed.  Common for optos)

    flipperLwR:
        number: SD0

    flipperLwL:
        number: SD1

# Coil numbering format: Ax-By-z:

# Capital letters are required, lower case letters represent the numbers:
# x : Board address (0-7)
# y : Bank address (0 for A, 1 for B)
# z : Output number (0-7)

PRCoils:
    flipperLwLMain: 
        number: A0-B1-0
    flipperLwLHold: 
        number: A0-B1-1
    flipperLwRMain: 
        number: A0-B1-2
    flipperLwRHold: 
        number: A0-B1-3
    slingl: 
        number: A0-B1-4
    slingr: 
        number: A3-B1-5

# Lamp numbering format: C-Ax-By-z:R-Am-Bn-p:

# Capital letters are required, lower case letters represent the numbers:
# For Columns (Source circuits - represented by the 'C')
# x : Column board address (0-7)
# y : Column bank address (0 for A, 1 for B)
# z : Output number (0-7)

# For Rows (Sink circuits - represented by the 'R')
# m : Row board address (0-7)
# n : Row bank address (0 for A, 1 for B)
# p : Output number (0-7)


PRLamps:
    VUK_right_r:
        number: C-A4-B0-0:R-A4-B1-0
    VUK_right_b:
        number: C-A4-B0-0:R-A4-B1-1
    VUK_right_g:
        number: C-A4-B0-0:R-A4-B1-2
    VUK_left_g:
        number: C-A4-B0-0:R-A4-B1-3
    VUK_left_b:
        number: C-A4-B0-0:R-A4-B1-4
    VUK_left_r:
        number: C-A4-B0-0:R-A4-B1-5

PRDriverGlobals:
    lamp_matrix_strobe_time: 200
    use_watchdog: True
    watchdog_time: 1000
