# P-ROC Game Description file for Twilight Zone
PRGame:
    machineType: wpc
PRFlippers:
    - flipperLwR
    - flipperLwL
    - flipperUpR
    - flipperUpL
PRBumpers:
    - slingL
    - slingR
PRSwitches:
    flipperLwR:
        number: SF2
    flipperLwL:
        number: SF4
    flipperUpR:
        number: SF6
    flipperUpL:
        number: SF8
    slingL:
        number: S34
    slingR: 
        number: S35
    outhole:
        number: S18
    troughFarLeft:
        number: S25
    troughLeft:
        number: S17
    troughMiddle:
        number: S16
    troughRight:
        number: S15
    shooterLane:
        number: S27
    startButton:
        number: S13
    rocketKickout:
        number: S28
    slotKickout:
        number: S58
PRCoils:
    flipperLwRMain: 
        number: 32
    flipperLwRHold: 
        number: 33
    flipperLwLMain: 
        number: 34
    flipperLwLHold: 
        number: 35
    flipperUpRMain: 
        number: 36
    flipperUpRHold: 
        number: 37
    flipperUpLMain: 
        number: 38
    flipperUpLHold: 
        number: 39
    slingL:
        number: C11
    slingR: 
        number: C10
    slotKickout:
        number: C01
    rocketKickout: 
        number: C02
    outhole:
        number: C08
    ballRelease:
        number: C09
PRLamps:
    startButton:
        number: L88
    doorTheCamera:
        number: L11